### ISSUE TITLE
Enhancement Request: Improved Auto-Suggestion Behavior

### ISSUE THREAD

**Issue by mustafa-shahriar** [kevinfengcs88/nvim#4]
When using auto-suggestions in Neovim, it would be more user-friendly if we could select the first suggestion by simply pressing Enter, rather than having to use the down arrow key. Can we consider this improvement?

**Comment by kevinfengcs88** [comment]
Simply change this line: https://github.com/kevinfengcs88/nvim/blob/master/lua/plugins/lsp.lua#L71 like so

```
['<CR>'] = cmp.mapping.confirm({ select = true }),
```

You might not want this behavior, however, since it will annoyingly autocomplete with the first suggestion (if there is one) when you try to create a new line. Imagine you're writing a line of code, get to the end, and hit ENTER, only to see that you autocompleted some bogus without having inserted a new line. 

Also you can use <C-n> and <C-p> to cycle next and previous in these types of menus. Much easier than moving your right hand to the arrow keys. With <C-n> and <C-p>, your fingers remain on the home row. May take some time getting used to, but <C-n> and <C-p> are quite common in a lot of Vim/Neovim configurations.

**Comment by mustafa-shahriar** [comment]
Thank you for addressing this issue, and it now appears to be fully resolved.
